// LOGIN
export const LOGIN_ON = "LOGIN_ON";

//DESARROLLO CONTANTS

export const DESARROLLO_SCREEN = "DESARROLLO_SCREEN";

export const DESARROLLO_INCREMENT = "DESARROLLO_INCREMENT";
export const DESARROLLO_DECREMENT = "DESARROLLO_DECREMENT";

export const GUARDAR_FILTROS = "GUARDAR_FILTROS";
export const GUARDAR_VISUALIZACION = "GUARDAR_VISUALIZACION";
export const SET_FILTROS_HABILITADOS = "SET_FILTROS_HABILITADOS";

export const DATA_DETALLE_GUARDAR = "DATA_DETALLE_GUARDAR";
export const DATA_DETALLE_GUARDAR_FILTRADA = "DATA_DETALLE_GUARDAR_FILTRADA";
export const DATA_DETALLE_GUARDAR_AGRUPADA = "DATA_DETALLE_GUARDAR_AGRUPADA";
export const DATA_DETALLE_SET_IS_LOADING = "DATA_DETALLE_SET_IS_LOADING";

export const SET_FILTROS_ACTUALIZADOS = "SET_FILTROS_ACTUALIZADOS";

export const GUARDAR_NAVIGATION_USER = "GUARDAR_NAVIGATION_USER";

export const GUARDAR_FILTRO_FECHA = "GUARDAR_FILTRO_FECHA";

export const GUARDAR_MODAL_UBICACION_VISIBLE = "GUARDAR_MODAL_UBICACION_VISIBLE";
export const GUARDAR_MODAL_FOTOS_VISIBLE = "GUARDAR_MODAL_FOTOS_VISIBLE";
export const GUARDAR_MODAL_UBICACION_DATA = "GUARDAR_MODAL_UBICACION_DATA";
export const GUARDAR_MODAL_FOTOS_DATA = "GUARDAR_MODAL_FOTOS_DATA";




